### ISSUE TITLE
Patterns with guards?

### ISSUE THREAD

**Issue by wooters** [santinic/pampy#10]
Very cool module! This is one of the things I like about scala and I'm excited to be able to use this in python.

I was wondering if there would be some way to allow for conditionals in the patterns? Something like this (but not necessarily using this syntax):

```
match(input,
    pattern_1 if cond_1, action_1,  # matches pattern_1 under condition cond_1
    pattern_1, action_1a,  # default matching for pattern_1
...
)
```
So, in this case, the first pattern wouldn't match the input unless `cond_1` was true. So, you could 
do something like:

```
match(x,
    int if x < 10, print("integer value less than 10"),
    int, print("integer value >= 10")
}
```

**Comment by santinic** [comment]
Hi Chuck, nice point. 
[Un]fortunately Python is not flexible enough to allow for this kind of syntax, so I we have to use lambdas for conditions. It's already supported and tested in pampy but not documented yet. I will add it. 

```python
cond = lambda x: x < 10
match(3, cond, "action", _, "else")    # => "action"
match(11, cond, "action1", _, "else")   # => "else"
```

So if you want to dive in lambda heaven:

```python
match(x,
    lambda x: x % 2 == 0, lambda x: "even %d" % x,
    lambda x: x % 2 != 0, lambda x: "odd %d" % x,
)
```
If you want to check for both type (`int`) and < 10 you need to lambda it manually:

```python
match(x,
    lambda x: type(x) == int and x % 2 == 0, lambda x: "even %d" % x,
    lambda x: type(x) == int and x % 2 != 0, lambda x: "odd %d" % x,
    str,                                     "string"
)
```

**Comment by wooters** [comment]
Cool, thanks for your response!
