### ISSUE TITLE
OneOf operator for matching

### ISSUE THREAD

**Issue by HarryR** [santinic/pampy#19]
Say I want to have a match for any one of the items, instead of creating two statements to match against we only need one which specifies that the value must be one within a set.

For example:

```python
class Choice(Enum):
	START = 0
	COOPERATE = 1
	DEFECT = 2

match(Choice.DEFECT, OneOf(Choice.DEFECT, Choice.COOPERATE), True)
```

This will make some types of rules more succinct, especially with support for the Enum type.

Sounds like a good idea?

**Comment by santinic** [comment]
Yeah, that sounds right to me :) feel free to implement it. Thanks Harry

**Comment by laike9m** [comment]
Feels like implementing one is easy enough, but still surprised to find it's not supported...

**Comment by adamlwgriffiths** [comment]
Did you get around to implementing this?
Looks like the pampy code isn't pluggable - in that adding new features requires modifying the internals, not just adding new types. https://github.com/santinic/pampy/blob/master/pampy/pampy.py#L59

**Comment by HarryR** [comment]
No, I'd forgotten about `pampy` until now, the type matching in Rust is adequate.
