### ISSUE TITLE
Typing support

### ISSUE THREAD

**Issue by sobolevn** [santinic/pampy#32]
Hi! Thanks for this library, it looks fun.

Does it support typing and mypy checks?
Are there any plans to support it?

**Comment by Ecialo** [comment]
Hi!
I already implement this feature in #26, but it currently not merged for some reasons.

**Comment by santinic** [comment]
Merged

**Comment by sobolevn** [comment]
@santinic awesome! But, this is not exactly I was asking about 🙂 

Sorry, I have to be more specific. I was asking about types for end users.
Like [PEP561](https://www.python.org/dev/peps/pep-0561/) declares.
