### ISSUE TITLE
Possible C module?

### ISSUE THREAD

**Issue by kimond** [santinic/pampy#4]
> Pampy is pretty small (150 lines), reasonably fast.

*Reasonably fast*

I didn't try pampy yet but I was wondering if a C native module would help to improve the speed?

[Numpy](https://github.com/numpy/numpy) has some parts written in C to improve performance.

This is just a minor suggestion. Perhaps it is completely useless.

**Comment by santinic** [comment]
Thanks Kim, but I don't think a C extensions would make much difference.
